/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnunciosRouteImport } from './routes/_authenticated/anuncios'
import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCompradorRouteImport } from './routes/_authenticated/comprador'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as ProdutorIdRouteImport } from './routes/produtor.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnunciosRoute = AuthenticatedAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBemVindoRoute = AuthenticatedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompradorRoute = AuthenticatedCompradorRouteImport.update({
  id: '/comprador',
  path: '/comprador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdutorIdRoute = ProdutorIdRouteImport.update({
  id: '/produtor/$id',
  path: '/produtor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comprador': typeof AuthenticatedCompradorRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anuncios': typeof AuthenticatedAnunciosRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comprador': typeof AuthenticatedCompradorRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anuncios': typeof AuthenticatedAnunciosRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/comprador': typeof AuthenticatedCompradorRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/produtor/$id': typeof ProdutorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anuncios'
    | '/bem-vindo'
    | '/buscar'
    | '/calendario'
    | '/comprador'
    | '/favoritos'
    | '/mensagens'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/relatorios'
    | '/seguranca'
    | '/simulador'
    | '/produtor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/anuncios'
    | '/bem-vindo'
    | '/buscar'
    | '/calendario'
    | '/comprador'
    | '/favoritos'
    | '/mensagens'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/relatorios'
    | '/seguranca'
    | '/simulador'
    | '/produtor/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anuncios'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/buscar'
    | '/_authenticated/calendario'
    | '/_authenticated/comprador'
    | '/_authenticated/favoritos'
    | '/_authenticated/mensagens'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/seguranca'
    | '/_authenticated/simulador'
    | '/produtor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProdutorIdRoute: typeof ProdutorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anuncios': {
      id: '/_authenticated/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AuthenticatedAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comprador': {
      id: '/_authenticated/comprador'
      path: '/comprador'
      fullPath: '/comprador'
      preLoaderRoute: typeof AuthenticatedCompradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produtor/$id': {
      id: '/produtor/$id'
      path: '/produtor/$id'
      fullPath: '/produtor/$id'
      preLoaderRoute: typeof ProdutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnunciosRoute: typeof AuthenticatedAnunciosRoute
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCompradorRoute: typeof AuthenticatedCompradorRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnunciosRoute: AuthenticatedAnunciosRoute,
  AuthenticatedBemVindoRoute: AuthenticatedBemVindoRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCompradorRoute: AuthenticatedCompradorRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProdutorIdRoute: ProdutorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
